version: "3"

services:
  app:
    # remove node_modules folder and start development server
    # command: sh -c "rm -rf /project/app/node_modules/* && npm run dev"
    container_name: website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/project/app/  # cannot mount the whole directory because of conflict with node_modules
      - exclude:/project/node_modules

volumes:
  exclude: